import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Scaffold</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex items-center">
        <div className="mx-auto">
          <h1 className="text-red-600">
            Welcome to Next.js!
          </h1>
        </div>
      </main>
    </div>
  )
}
